# Generated by Django 3.2.7 on 2021-09-26 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('zipcode', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{5}(?:-[0-9]{4})?$')])),
                ('city', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
