# Generated by Django 3.2.7 on 2021-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='phone',
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.TextField(blank=True),
        ),
    ]
